version: 2.1

jobs:
  test_job:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python3 manage.py test open_weather_api --settings=open_weather_project.test_settings

  deploy_weather_job:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT"
      - run:
          name: SSH and Deploy
          command: |
            ssh -v -o StrictHostKeyChecking=no wcezar@$SERVER_ADDRESS "bash /path/to/deploy_weather.sh"

workflows:
  test_and_deploy_workflow:
    jobs:
      - test_job
      - deploy_weather_job:
          requires:
            - test_job
          filters:
            branches:
              only:
                - master
